# Generated by Django 4.0.6 on 2022-07-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_total',
            field=models.IntegerField(default=0),
        ),
    ]
