# Generated by Django 4.0.6 on 2022-07-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_tag_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
