# Generated by Django 4.0.6 on 2022-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profileimg',
            field=models.ImageField(default='r.jpg', upload_to='comment_images'),
            preserve_default=False,
        ),
    ]
