# Generated by Django 4.0.6 on 2022-07-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_comment_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
